version: '2'
services:
  myapp:
    image: 'bitnami/codeigniter:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:8000'
    volumes:
      - '.:/app'
    depends_on:
      - mariadb
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CODEIGNITER_PROJECT_NAME=tenantc-site
